### ISSUE TITLE
modules_csh_path should be /etc/csh/login.d/modules.csh on Ubuntu

### ISSUE THREAD

**Issue by jabl** [treydock/puppet-lmod#2]
Hi,

tcsh on Ubuntu 14.04 seems to by default source files from /etc/csh/login.d instead of /etc/profile.d. Would be nice if this module could by default point to the right location. 

One cannot change it unilaterally, since on redhat-based systems tcsh uses /etc/profile.d. So there would need to be a parameter that is different for different distros.

**Comment by treydock** [comment]
Resolved with #5
