### ISSUE TITLE
incorrect examples in your readme

### ISSUE THREAD

**Issue by djgreen** [treydock/puppet-lmod#29]
You make multiple references to "moduleroot_path" 
Pretty sure you mean "modulepath_root"

--Dan

**Comment by djgreen** [comment]
You also use "avail_style" where it should be "avail_styles"

**Comment by treydock** [comment]
Fixed with https://github.com/treydock/puppet-lmod/commit/62fe9e16e545d22cb638ef5ffae6954ce40a3478
