### ISSUE TITLE
module cmd not found on Ubuntu (local)

### ISSUE THREAD

**Issue by djgreen** [treydock/puppet-lmod#33]
Here's another interesting one for you... when pushing to Ubuntu systems, we've found that when you remotely ssh into the system, module/ml is found. 

But if you locally login to the workstation, and start terminal, command not found.

**Comment by treydock** [comment]
I don't have much experience with Ubuntu or Debian systems, if it was RHEL I'd say check `/etc/profile` and `/etc/bashrc` to make sure it's still iterating over all `*.sh` files in `/etc/profile.d/`. For Ubuntu I have no clue how all that works.  It sounds like whatever environment initialization is taking place for local logins is not loading files in `/etc/profile.d/`

**Comment by treydock** [comment]
If you get a local logic, does `bash --login` give you a shell that does have module/ml functions defined?  That's only a work around, still curious why it's not automatic when you log in.

**Comment by djgreen** [comment]
Yeah, confirmed that's the issue. The terminal cmd needs to have the "Run command as a login shell" option checked. When it is, this is fixed. Need to look at our configurations.

**Comment by djgreen** [comment]
I've confirmed that Fedora/RHEL will pull from /etc/profile.d when launching both login and non-login shells. 

However, Debian does not. Only in login shells. Hence the need to alter the gnome-terminal settings to tell it to run as a login shell on Ubuntu. But having to expect every end user to know/remember to do that on each computer they login to so they can use lmod isn't very feasible. 

I'm trying to look at alternatives we can set.

**Comment by djgreen** [comment]
Might be off on this... the local terminal when I run "env" does have a lot of the LMOD variables set... so it is running /etc/profile.d/lmod.sh --- unless it could be pulling that info from somewhere else... 

But I think it might be failing the last part of the lmod.sh:

>  my_shell=$($PS_CMD -p $$ -ocomm=)
>   my_shell=$($EXPR_CMD    "$my_shell" : '-*\(.*\)')
>   my_shell=$($BASENAME_CMD $my_shell)
>   if [ -f /usr/share/lmod/lmod/init/$my_shell ]; then
>      .    /usr/share/lmod/lmod/init/$my_shell >/dev/null # Module Support
>   else
>      .    /usr/share/lmod/lmod/init/sh        >/dev/null # Module Support
>   fi

I say this because here's the diff when I run env from non-login terminal on Gnome/Ubuntu I'm missing these lines at the end:

BASH_FUNC_ml%%=() {  eval $($LMOD_DIR/ml_cmd "$@")
}
BASH_FUNC_module%%=() {  eval $($LMOD_CMD bash "$@");
 [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}

When I run _ps -p $$ -ocomm=_ from an ssh (login shell) to the Ubuntu box, the results are

> bash

But from the non-login terminal in Gnome, I get:

> COMMAND
bash

Which is causing making your scripts default to calling /usr/share/lmod/lmod/init/sh >/dev/null instead of /usr/share/lmod/lmod/init/bash >/dev/null

If the script can be adjusted to take that into account, I think we'd be fine.

**Comment by djgreen** [comment]
Or not... even if you manually force the script to always use bash, the experience is still broken... 

The way you're adding lmod to the shell requires it to be done at the creation of the shell... so even though the script was called by Gnome and all of the env vars are already setup, the /usr/share/lmod/lmod/init/bash has to be called every time... 

And since non-login shells don't reference /etc/profile.d, we're back to where we were.

**Comment by djgreen** [comment]
Which the lmod folks point out... 
https://lmod.readthedocs.io/en/latest/030_installing.html#bash-under-ubuntu

**Comment by djgreen** [comment]
So perhaps we need a variable that triggers that addition to /etc/bash.bashrc

**Comment by treydock** [comment]
Adding multiple lines to a file that is not directly managed by Puppet is challenging.  I have what I hope is a working solution in #35.  Because file_line only operates on a single line, had to condense everything down to a single line so it's really ugly but it works.

**Comment by treydock** [comment]
The acceptance tests for #35 passed but they don't trigger this new code. Let me know if you're able to test #35 and if it works for you.

**Comment by djgreen** [comment]
Thanks for the attempt. But in talking with our Linux Admin, I think you're right to suggest that we make this change outside of the module as it'll impact more than just lmod.

**Comment by treydock** [comment]
That works.  I'll close out #35 , if you end up needing it or maybe something more targeted to just Lmod , let me know.
