### ISSUE TITLE
puppet error on Ubuntu 20 LTS

### ISSUE THREAD

**Issue by djgreen** [treydock/puppet-lmod#38]
> Error: Could not set 'file' on ensure: No such file or directory - A directory component in /etc/csh/login.d/lmod.csh20220420-10341-1vpkbzp.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/ece_production/modules/lmod/manifests/load.pp, line: 49)
> Error: Could not set 'file' on ensure: No such file or directory - A directory component in /etc/csh/login.d/lmod.csh20220420-10341-1vpkbzp.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/ece_production/modules/lmod/manifests/load.pp, line: 49)
> Wrapped exception:
> No such file or directory - A directory component in /etc/csh/login.d/lmod.csh20220420-10341-1vpkbzp.lock does not exist or is a dangling symbolic link
> Error: /Stage[main]/Lmod::Load/File[lmod-csh-load]/ensure: change from 'absent' to 'file' failed: Could not set 'file' on ensure: No such file or directory - A directory component in /etc/csh/login.d/lmod.csh20220420-10341-1vpkbzp.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/ece_production/modules/lmod/manifests/load.pp, line: 49)

Noticing the above error when running on Ubuntu 20 LTS.

**Comment by djgreen** [comment]
Nevermind, realized that I wasn't installing csh or tcsh on my Ubuntu 20 systems. When I forced this, the issue went away.

Of course, not sure that it should be required if we weren't using it...

**Comment by treydock** [comment]
Did you happen to define a different list of runtime packages?  This module should have already handled install csh and tcsh unless that list of packages was re-defined.

**Comment by djgreen** [comment]
We haven't changed any of your code if that's what you're asking. We just call it. Where in your code do you force the installation of those packages?

**Comment by djgreen** [comment]
Checked our config, and yes, we're using "install_method  => 'package',"

**Comment by treydock** [comment]
Fix for this will be released with v3.2.0 once Github Actions complete.
